# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJEvEnqrH5gatCdoqHJg3IisQWXNno0e
"""

!pip install pandas numpy matplotlib seaborn scikit-learn statsmodels fbprophet xgboost tensorflow

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Loading the dataset
df = pd.read_csv('/content/drive/MyDrive/household_power_consumption.csv', sep=';', low_memory=False)

# Displaying the first few rows
df.head()

"""Data Preprocessing"""

# Combining 'Date' and 'Time' columns into a single 'DateTime' column
df['DateTime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], format='%d/%m/%Y %H:%M:%S')

# Setting 'DateTime' as the index
df.set_index('DateTime', inplace=True)

# Dropping the original 'Date' and 'Time' columns as they are no longer needed
df.drop(columns=['Date', 'Time'], inplace=True)

# Displaying the first few rows to verify
df.head()

#Checking for missing values
df.isnull().sum()

df.ffill(inplace=True)
df.isnull().sum()